application: pastlog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /winterbells
  static_dir: static/winterbells

- url: /jstetris
  static_dir: static/JsTetris

- url: /thelostvikings
  static_dir: static/thelostvikings

- url: /linux/
  static_dir: static/jslinux

- url: /.*
  script: log.app

libraries:
- name: django
  version: "1.2"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'