application: lostab
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /winterbells
  static_dir: static/winterbells

- url: /jstetris
  static_dir: static/JsTetris

- url: /.*
  script: lostab.py